CREATE DATABASE IF NOT EXISTS smms;
USE smms;

DROP TABLE IF EXISTS MODULE_INTEGRATION;
DROP TABLE IF EXISTS MISSION_ASSIGNMENT;
DROP TABLE IF EXISTS SPACECRAFT_MISSION;
DROP TABLE IF EXISTS EXPERIMENT_EXECUTION;
DROP TABLE IF EXISTS ALERT;
DROP TABLE IF EXISTS SYSTEM_STATUS;
DROP TABLE IF EXISTS ENVIRONMENTAL_DATA;
DROP TABLE IF EXISTS NAVIGATION_DATA;
DROP TABLE IF EXISTS TELEMETRY_DATA;
DROP TABLE IF EXISTS SCHEDULED_EVENT;
DROP TABLE IF EXISTS BIOLOGICAL;
DROP TABLE IF EXISTS PHYSICAL;
DROP TABLE IF EXISTS ASTRONOMY;
DROP TABLE IF EXISTS ENGINEERING_EXP;
DROP TABLE IF EXISTS EXPERIMENT;
DROP TABLE IF EXISTS HABITAT;
DROP TABLE IF EXISTS LABORATORY;
DROP TABLE IF EXISTS MODULE;
DROP TABLE IF EXISTS ROCKET;
DROP TABLE IF EXISTS SHUTTLE;
DROP TABLE IF EXISTS CAPSULE;
DROP TABLE IF EXISTS EQUIPMENT;
DROP TABLE IF EXISTS SPACECRAFT;
DROP TABLE IF EXISTS MISSION;
DROP TABLE IF EXISTS SPACE_STATION;
DROP TABLE IF EXISTS ASTRONAUT;
DROP TABLE IF EXISTS GROUND_CONTROL;
DROP TABLE IF EXISTS PERSON;

CREATE TABLE PERSON (
  PersonID INT PRIMARY KEY AUTO_INCREMENT,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  DateOfBirth DATE NOT NULL,
  Gender VARCHAR(10) CHECK (Gender IN ('M', 'F', 'Other')),
  Nationality VARCHAR(50) NOT NULL,
  ContactInfo VARCHAR(100)
);

CREATE TABLE ASTRONAUT (
  PersonID INT PRIMARY KEY,
  FlightHours DECIMAL(8,2) DEFAULT 0,
  Role VARCHAR(50) NOT NULL,
  Specialization VARCHAR(100),
  ClearanceLevel VARCHAR(20),
  SpaceSuitSize VARCHAR(10),
  Department VARCHAR(50),
  `Rank` VARCHAR(30),
  HealthStatus VARCHAR(50),
  ConsoleAssignment VARCHAR(50),
  ShiftSchedule VARCHAR(50),
  MentorID INT NULL,
  CONSTRAINT FK_ASTRONAUT_PERSON FOREIGN KEY (PersonID) REFERENCES PERSON(PersonID) ON DELETE CASCADE,
  CONSTRAINT FK_ASTRONAUT_MENTOR FOREIGN KEY (MentorID) REFERENCES ASTRONAUT(PersonID) ON DELETE SET NULL
);

CREATE TABLE GROUND_CONTROL (
  PersonID INT PRIMARY KEY,
  Role VARCHAR(50) NOT NULL,
  Department VARCHAR(50),
  ShiftSchedule VARCHAR(50),
  ConsoleAssignment VARCHAR(50),
  ClearanceLevel VARCHAR(20),
  CONSTRAINT FK_GROUND_CONTROL_PERSON FOREIGN KEY (PersonID) REFERENCES PERSON(PersonID) ON DELETE CASCADE
);

CREATE TABLE SPACE_STATION (
  StationID INT PRIMARY KEY AUTO_INCREMENT,
  StationName VARCHAR(100) NOT NULL UNIQUE,
  LaunchDate DATE,
  OrbitAltitude DECIMAL(10,2),
  OrbitalInclination DECIMAL(5,2),
  PowerGeneration DECIMAL(10,2),
  MaxCrewCapacity INT,
  InternationalPartners VARCHAR(200),
  CurrentStatus VARCHAR(50)
);

CREATE TABLE MODULE (
  ModuleID INT PRIMARY KEY AUTO_INCREMENT,
  StationID INT NULL,
  Name VARCHAR(100) NOT NULL,
  Manufacturer VARCHAR(100),
  LaunchMass DECIMAL(10,2),
  LaunchDate DATE,
  Dimensions VARCHAR(100),
  CONSTRAINT FK_MODULE_STATION FOREIGN KEY (StationID) REFERENCES SPACE_STATION(StationID) ON DELETE SET NULL
);

CREATE TABLE HABITAT (
  ModuleID INT PRIMARY KEY,
  SleepingQuarters INT,
  ExerciseEquipment VARCHAR(100),
  GalleyFacilities VARCHAR(100),
  LifeSupportCapacity INT,
  CONSTRAINT FK_HABITAT_MODULE FOREIGN KEY (ModuleID) REFERENCES MODULE(ModuleID) ON DELETE CASCADE
);

CREATE TABLE LABORATORY (
  ModuleID INT PRIMARY KEY,
  ResearchFocus VARCHAR(150),
  CleanRoomLevel VARCHAR(50),
  SampleStorage VARCHAR(100),
  EquipmentList TEXT,
  CONSTRAINT FK_LAB_MODULE FOREIGN KEY (ModuleID) REFERENCES MODULE(ModuleID) ON DELETE CASCADE
);

CREATE TABLE SPACECRAFT (
  SpacecraftID INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(100) NOT NULL UNIQUE,
  Manufacturer VARCHAR(100),
  Status VARCHAR(50),
  MaxCrewCapacity INT,
  MaxPayloadMass DECIMAL(12,2),
  LaunchDate DATE
);

CREATE TABLE CAPSULE (
  SpacecraftID INT PRIMARY KEY,
  DockingPorts INT,
  LandingGear VARCHAR(50),
  HeatShieldType VARCHAR(50),
  CrewCapacity INT,
  CONSTRAINT FK_CAPSULE_SPACECRAFT FOREIGN KEY (SpacecraftID) REFERENCES SPACECRAFT(SpacecraftID) ON DELETE CASCADE
);

CREATE TABLE SHUTTLE (
  SpacecraftID INT PRIMARY KEY,
  CargoBaySize DECIMAL(10,2),
  Wingspan DECIMAL(10,2),
  CrewCapacity INT,
  CONSTRAINT FK_SHUTTLE_SPACECRAFT FOREIGN KEY (SpacecraftID) REFERENCES SPACECRAFT(SpacecraftID) ON DELETE CASCADE
);

CREATE TABLE ROCKET (
  SpacecraftID INT PRIMARY KEY,
  StageCount INT,
  BoosterCount INT,
  Reusable BOOLEAN,
  CONSTRAINT FK_ROCKET_SPACECRAFT FOREIGN KEY (SpacecraftID) REFERENCES SPACECRAFT(SpacecraftID) ON DELETE CASCADE
);

CREATE TABLE MISSION (
  MissionID INT PRIMARY KEY AUTO_INCREMENT,
  MissionName VARCHAR(100) NOT NULL UNIQUE,
  MissionType VARCHAR(50) NOT NULL,
  MissionObjective TEXT,
  LaunchDateTime DATETIME NOT NULL,
  EstimatedDuration DECIMAL(6,2),
  ActualDuration DECIMAL(6,2),
  Budget DECIMAL(15,2),
  RiskLevel VARCHAR(20) CHECK (RiskLevel IN ('Low', 'Medium', 'High', 'Critical')),
  MissionStatus VARCHAR(30) NOT NULL DEFAULT 'Planned'
);

CREATE TABLE EXPERIMENT (
  ExperimentID INT PRIMARY KEY AUTO_INCREMENT,
  Title VARCHAR(120) NOT NULL,
  Objective TEXT,
  StartDate DATE,
  EndDate DATE,
  Status VARCHAR(40),
  PrincipalInvestigator VARCHAR(100)
);

CREATE TABLE BIOLOGICAL (
  ExperimentID INT PRIMARY KEY,
  SpecimenType VARCHAR(80),
  Containment VARCHAR(80),
  CrewImpact VARCHAR(80),
  CONSTRAINT FK_BIO_EXP FOREIGN KEY (ExperimentID) REFERENCES EXPERIMENT(ExperimentID) ON DELETE CASCADE
);

CREATE TABLE PHYSICAL (
  ExperimentID INT PRIMARY KEY,
  PhysicsType VARCHAR(80),
  PhysicsPrecision VARCHAR(40),
  DataRate VARCHAR(40),
  CONSTRAINT FK_PHY_EXP FOREIGN KEY (ExperimentID) REFERENCES EXPERIMENT(ExperimentID) ON DELETE CASCADE
);

CREATE TABLE ASTRONOMY (
  ExperimentID INT PRIMARY KEY,
  SkyRegion VARCHAR(80),
  TelescopeUsed VARCHAR(80),
  Wavelength VARCHAR(40),
  ExposureTime VARCHAR(40),
  CONSTRAINT FK_ASTRO_EXP FOREIGN KEY (ExperimentID) REFERENCES EXPERIMENT(ExperimentID) ON DELETE CASCADE
);

CREATE TABLE ENGINEERING_EXP (
  ExperimentID INT PRIMARY KEY,
  TestObjective VARCHAR(120),
  SafetyMargin VARCHAR(40),
  RedundancyLevel VARCHAR(40),
  StressFactors VARCHAR(120),
  CONSTRAINT FK_ENG_EXP FOREIGN KEY (ExperimentID) REFERENCES EXPERIMENT(ExperimentID) ON DELETE CASCADE
);

CREATE TABLE TELEMETRY_DATA (
  TelemetryID INT PRIMARY KEY AUTO_INCREMENT,
  SpacecraftID INT NOT NULL,
  MissionID INT NOT NULL,
  Timestamp DATETIME NOT NULL,
  DataQuality VARCHAR(40),
  SourceSystem VARCHAR(80),
  CONSTRAINT FK_TELEM_SPACECRAFT FOREIGN KEY (SpacecraftID) REFERENCES SPACECRAFT(SpacecraftID) ON DELETE RESTRICT,
  CONSTRAINT FK_TELEM_MISSION FOREIGN KEY (MissionID) REFERENCES MISSION(MissionID) ON DELETE RESTRICT
);

CREATE TABLE SYSTEM_STATUS (
  TelemetryID INT PRIMARY KEY,
  Temperature DECIMAL(6,2),
  Humidity DECIMAL(6,2),
  CPUUsage DECIMAL(6,2),
  PowerLevel DECIMAL(6,2),
  OxygenLevel DECIMAL(6,2),
  Pressure DECIMAL(8,2),
  MemoryUsage DECIMAL(6,2),
  CommStatus VARCHAR(50),
  CONSTRAINT FK_SYS_TELEM FOREIGN KEY (TelemetryID) REFERENCES TELEMETRY_DATA(TelemetryID) ON DELETE CASCADE
);

CREATE TABLE ENVIRONMENTAL_DATA (
  TelemetryID INT PRIMARY KEY,
  Temperature DECIMAL(6,2),
  Humidity DECIMAL(6,2),
  Pressure DECIMAL(8,2),
  OxygenLevel DECIMAL(6,2),
  Radiation DECIMAL(8,2),
  CONSTRAINT FK_ENV_TELEM FOREIGN KEY (TelemetryID) REFERENCES TELEMETRY_DATA(TelemetryID) ON DELETE CASCADE
);

CREATE TABLE NAVIGATION_DATA (
  TelemetryID INT PRIMARY KEY,
  PositionX DECIMAL(12,4),
  PositionY DECIMAL(12,4),
  PositionZ DECIMAL(12,4),
  Velocity DECIMAL(12,4),
  Orientation VARCHAR(80),
  TransmissionDelay DECIMAL(8,3),
  ErrorCodes VARCHAR(120),
  CONSTRAINT FK_NAV_TELEM FOREIGN KEY (TelemetryID) REFERENCES TELEMETRY_DATA(TelemetryID) ON DELETE CASCADE
);

CREATE TABLE ALERT (
  AlertID INT PRIMARY KEY AUTO_INCREMENT,
  TelemetryID INT,
  AlertType VARCHAR(50),
  Severity VARCHAR(20) CHECK (Severity IN ('Low', 'Medium', 'High', 'Critical')),
  Timestamp DATETIME,
  Message TEXT,
  Acknowledged BOOLEAN DEFAULT FALSE,
  RootCause TEXT,
  ResolutionTime DATETIME,
  CONSTRAINT FK_ALERT_TELEM FOREIGN KEY (TelemetryID) REFERENCES TELEMETRY_DATA(TelemetryID) ON DELETE SET NULL
);

CREATE TABLE SCHEDULED_EVENT (
  EventID INT PRIMARY KEY AUTO_INCREMENT,
  MissionID INT,
  AlertID INT NULL,
  ExperimentID INT NULL,
  PersonID INT NULL,
  PrecedingEventID INT NULL,
  EventType VARCHAR(60),
  Description TEXT,
  PlannedStartTime DATETIME,
  PlannedDuration DECIMAL(8,2),
  ActualStartTime DATETIME,
  ActualDuration DECIMAL(8,2),
  Criticality VARCHAR(20),
  Status VARCHAR(40),
  CONSTRAINT FK_EVENT_MISSION FOREIGN KEY (MissionID) REFERENCES MISSION(MissionID) ON DELETE RESTRICT,
  CONSTRAINT FK_EVENT_ALERT FOREIGN KEY (AlertID) REFERENCES ALERT(AlertID) ON DELETE SET NULL,
  CONSTRAINT FK_EVENT_EXP FOREIGN KEY (ExperimentID) REFERENCES EXPERIMENT(ExperimentID) ON DELETE SET NULL,
  CONSTRAINT FK_EVENT_GC FOREIGN KEY (PersonID) REFERENCES GROUND_CONTROL(PersonID) ON DELETE SET NULL,
  CONSTRAINT FK_EVENT_PRECEDING FOREIGN KEY (PrecedingEventID) REFERENCES SCHEDULED_EVENT(EventID) ON DELETE SET NULL
);

CREATE TABLE EQUIPMENT (
  EquipmentID INT PRIMARY KEY AUTO_INCREMENT,
  StationID INT NULL,
  SpacecraftID INT NULL,
  EquipmentName VARCHAR(100) NOT NULL,
  EquipmentType VARCHAR(60) NOT NULL,
  SerialNumber VARCHAR(80) UNIQUE,
  Manufacturer VARCHAR(100),
  Status VARCHAR(40),
  Location VARCHAR(120),
  CalibrationDate DATE,
  WarrantyExpiry DATE,
  PurchaseDate DATE,
  CONSTRAINT FK_EQUIP_STATION FOREIGN KEY (StationID) REFERENCES SPACE_STATION(StationID) ON DELETE SET NULL,
  CONSTRAINT FK_EQUIP_SPACECRAFT FOREIGN KEY (SpacecraftID) REFERENCES SPACECRAFT(SpacecraftID) ON DELETE SET NULL
);

CREATE TABLE MISSION_ASSIGNMENT (
  AssignmentID INT PRIMARY KEY AUTO_INCREMENT,
  MissionID INT NOT NULL,
  AstronautID INT NOT NULL,
  Role VARCHAR(50),
  AssignmentDate DATE,
  EVAHoursPlanned DECIMAL(6,2),
  PrimaryResponsibility VARCHAR(120),
  TrainingCompletionDate DATE,
  Status VARCHAR(40),
  CONSTRAINT FK_ASSIGN_MISSION FOREIGN KEY (MissionID) REFERENCES MISSION(MissionID) ON DELETE RESTRICT,
  CONSTRAINT FK_ASSIGN_ASTRONAUT FOREIGN KEY (AstronautID) REFERENCES ASTRONAUT(PersonID) ON DELETE RESTRICT
);

CREATE TABLE SPACECRAFT_MISSION (
  SMCID INT PRIMARY KEY AUTO_INCREMENT,
  MissionID INT NOT NULL,
  SpacecraftID INT NOT NULL,
  RoleInMission VARCHAR(60),
  LaunchConfiguration VARCHAR(100),
  ReentryDate DATETIME,
  LandingSite VARCHAR(100),
  ReturnMass DECIMAL(12,2),
  ActualLaunchMass DECIMAL(12,2),
  CONSTRAINT FK_SMC_MISSION FOREIGN KEY (MissionID) REFERENCES MISSION(MissionID) ON DELETE RESTRICT,
  CONSTRAINT FK_SMC_SPACECRAFT FOREIGN KEY (SpacecraftID) REFERENCES SPACECRAFT(SpacecraftID) ON DELETE RESTRICT
);

CREATE TABLE EXPERIMENT_EXECUTION (
  ExecutionID INT PRIMARY KEY AUTO_INCREMENT,
  MissionID INT NOT NULL,
  ExperimentID INT NOT NULL,
  ScheduledStart DATETIME,
  ScheduledEnd DATETIME,
  ActualStart DATETIME,
  ActualEnd DATETIME,
  SuccessRating INT,
  Notes TEXT,
  EquipmentUsed TEXT,
  Location VARCHAR(100),
  DataVolumeGenerated DECIMAL(12,2),
  CONSTRAINT FK_EXEC_MISSION FOREIGN KEY (MissionID) REFERENCES MISSION(MissionID) ON DELETE RESTRICT,
  CONSTRAINT FK_EXEC_EXP FOREIGN KEY (ExperimentID) REFERENCES EXPERIMENT(ExperimentID) ON DELETE RESTRICT
);

CREATE TABLE MODULE_INTEGRATION (
  IntegrationID INT PRIMARY KEY AUTO_INCREMENT,
  ModuleID INT NOT NULL,
  StationID INT NOT NULL,
  DockingDate DATETIME,
  UndockingDate DATETIME,
  DockingPort VARCHAR(40),
  ConnectionType VARCHAR(40),
  LifeSupportIntegration VARCHAR(40),
  DataLinkStatus VARCHAR(40),
  PowerIntegrationStatus VARCHAR(40),
  CONSTRAINT FK_MI_MODULE FOREIGN KEY (ModuleID) REFERENCES MODULE(ModuleID) ON DELETE RESTRICT,
  CONSTRAINT FK_MI_STATION FOREIGN KEY (StationID) REFERENCES SPACE_STATION(StationID) ON DELETE RESTRICT
);

CREATE INDEX IDX_MODULE_StationID ON MODULE(StationID);
CREATE INDEX IDX_TELEM_MissionID ON TELEMETRY_DATA(MissionID);
CREATE INDEX IDX_TELEM_SpacecraftID ON TELEMETRY_DATA(SpacecraftID);
CREATE INDEX IDX_ALERT_Severity ON ALERT(Severity);
CREATE INDEX IDX_EQUIP_Status ON EQUIPMENT(Status);
CREATE INDEX IDX_MISSION_Status ON MISSION(MissionStatus);
CREATE INDEX IDX_ASSIGN_MissionID ON MISSION_ASSIGNMENT(MissionID);
CREATE INDEX IDX_ASSIGN_AstronautID ON MISSION_ASSIGNMENT(AstronautID);
