/** Entity registry: table, PK, search (LIKE), optional exact filters (?Col=), optional sort whitelist */
module.exports = {
  persons: {
    table: "PERSON",
    pk: "PersonID",
    searchable: ["FirstName", "LastName", "Nationality"],
    filters: [],
    sortable: ["PersonID", "LastName", "FirstName", "DateOfBirth"],
  },
  astronauts: {
    table: "ASTRONAUT",
    pk: "PersonID",
    searchable: ["Role", "Department", "Rank"],
    filters: ["Role", "Department", "HealthStatus"],
    sortable: ["PersonID", "Role", "Rank", "FlightHours"],
  },
  ground_control: {
    table: "GROUND_CONTROL",
    pk: "PersonID",
    searchable: ["Role", "Department"],
    filters: ["Role", "Department"],
    sortable: ["PersonID", "Role"],
  },
  missions: {
    table: "MISSION",
    pk: "MissionID",
    searchable: ["MissionName", "MissionType", "MissionStatus"],
    filters: ["MissionStatus", "MissionType", "RiskLevel"],
    sortable: ["MissionID", "MissionName", "LaunchDateTime", "MissionStatus", "Budget"],
  },
  spacecraft: {
    table: "SPACECRAFT",
    pk: "SpacecraftID",
    searchable: ["Name", "Manufacturer", "Status"],
    filters: ["Status", "Manufacturer"],
    sortable: ["SpacecraftID", "Name", "Status", "LaunchDate"],
  },
  stations: {
    table: "SPACE_STATION",
    pk: "StationID",
    searchable: ["StationName", "CurrentStatus"],
    filters: ["CurrentStatus"],
    sortable: ["StationID", "StationName", "OrbitAltitude"],
  },
  modules: {
    table: "MODULE",
    pk: "ModuleID",
    searchable: ["Name", "Manufacturer"],
    filters: ["StationID"],
    sortable: ["ModuleID", "Name", "LaunchDate"],
  },
  experiments: {
    table: "EXPERIMENT",
    pk: "ExperimentID",
    searchable: ["Title", "Status", "PrincipalInvestigator"],
    filters: ["Status"],
    sortable: ["ExperimentID", "Title", "StartDate", "Status"],
  },
  telemetry: {
    table: "TELEMETRY_DATA",
    pk: "TelemetryID",
    searchable: ["DataQuality", "SourceSystem"],
    filters: ["SpacecraftID", "MissionID"],
    sortable: ["TelemetryID", "Timestamp"],
  },
  alerts: {
    table: "ALERT",
    pk: "AlertID",
    searchable: ["AlertType", "Severity", "Message"],
    filters: ["Severity", "Acknowledged"],
    sortable: ["AlertID", "Timestamp", "Severity"],
  },
  equipment: {
    table: "EQUIPMENT",
    pk: "EquipmentID",
    searchable: ["EquipmentName", "EquipmentType", "Status", "Location"],
    filters: ["EquipmentType", "Status"],
    sortable: ["EquipmentID", "EquipmentName", "CalibrationDate"],
  },
  events: {
    table: "SCHEDULED_EVENT",
    pk: "EventID",
    searchable: ["EventType", "Criticality", "Status"],
    filters: ["MissionID", "Criticality", "Status", "EventType"],
    sortable: ["EventID", "PlannedStartTime", "Criticality"],
  },
  mission_assignments: {
    table: "MISSION_ASSIGNMENT",
    pk: "AssignmentID",
    searchable: ["Role", "Status"],
    filters: ["MissionID", "AstronautID"],
    sortable: ["AssignmentID", "AssignmentDate"],
  },
  spacecraft_missions: {
    table: "SPACECRAFT_MISSION",
    pk: "SMCID",
    searchable: ["RoleInMission"],
    filters: ["MissionID", "SpacecraftID"],
    sortable: ["SMCID"],
  },
  experiment_executions: {
    table: "EXPERIMENT_EXECUTION",
    pk: "ExecutionID",
    searchable: ["Location", "Notes"],
    filters: ["MissionID", "ExperimentID"],
    sortable: ["ExecutionID", "ScheduledStart"],
  },
  module_integrations: {
    table: "MODULE_INTEGRATION",
    pk: "IntegrationID",
    searchable: ["DockingPort", "ConnectionType"],
    filters: ["ModuleID", "StationID"],
    sortable: ["IntegrationID", "DockingDate"],
  },
  /* Subtype / auxiliary tables (PRD TPT) — used by specialized frontend tabs */
  capsules: {
    table: "CAPSULE",
    pk: "SpacecraftID",
    searchable: [],
    filters: [],
    sortable: ["SpacecraftID"],
  },
  shuttles: {
    table: "SHUTTLE",
    pk: "SpacecraftID",
    searchable: [],
    filters: [],
    sortable: ["SpacecraftID"],
  },
  rockets: {
    table: "ROCKET",
    pk: "SpacecraftID",
    searchable: [],
    filters: [],
    sortable: ["SpacecraftID"],
  },
  habitats: {
    table: "HABITAT",
    pk: "ModuleID",
    searchable: [],
    filters: [],
    sortable: ["ModuleID"],
  },
  laboratories: {
    table: "LABORATORY",
    pk: "ModuleID",
    searchable: [],
    filters: [],
    sortable: ["ModuleID"],
  },
  biological: {
    table: "BIOLOGICAL",
    pk: "ExperimentID",
    searchable: [],
    filters: [],
    sortable: ["ExperimentID"],
  },
  physical: {
    table: "PHYSICAL",
    pk: "ExperimentID",
    searchable: [],
    filters: [],
    sortable: ["ExperimentID"],
  },
  astronomy: {
    table: "ASTRONOMY",
    pk: "ExperimentID",
    searchable: [],
    filters: [],
    sortable: ["ExperimentID"],
  },
  engineering_exp: {
    table: "ENGINEERING_EXP",
    pk: "ExperimentID",
    searchable: [],
    filters: [],
    sortable: ["ExperimentID"],
  },
  system_status: {
    table: "SYSTEM_STATUS",
    pk: "TelemetryID",
    searchable: [],
    filters: ["TelemetryID"],
    sortable: ["TelemetryID"],
  },
  environmental_data: {
    table: "ENVIRONMENTAL_DATA",
    pk: "TelemetryID",
    searchable: [],
    filters: ["TelemetryID"],
    sortable: ["TelemetryID"],
  },
  navigation_data: {
    table: "NAVIGATION_DATA",
    pk: "TelemetryID",
    searchable: [],
    filters: ["TelemetryID"],
    sortable: ["TelemetryID"],
  },
};
