import {
  LayoutDashboard,
  Users,
  UserCheck,
  Headset,
  Rocket,
  Plane,
  Building2,
  Box,
  Microscope,
  Activity,
  AlertTriangle,
  Wrench,
  CalendarDays,
  ClipboardList,
  Sparkles,
  FlaskConical,
  Link2,
  UserCog,
  User,
} from "lucide-react";

/** Sidebar navigation — PRD §7.2 routes + professional lucide icons */
export const navItems = [
  { to: "/", label: "Dashboard", icon: <LayoutDashboard size={18} /> },
  { to: "/persons", label: "Persons", icon: <Users size={18} /> },
  { to: "/astronauts", label: "Astronauts", icon: <UserCheck size={18} /> },
  { to: "/ground-control", label: "Ground Control", icon: <Headset size={18} /> },
  { to: "/missions", label: "Missions", icon: <Rocket size={18} /> },
  { to: "/spacecraft", label: "Spacecraft", icon: <Plane size={18} /> },
  { to: "/stations", label: "Space Stations", icon: <Building2 size={18} /> },
  { to: "/modules", label: "Modules", icon: <Box size={18} /> },
  { to: "/experiments", label: "Experiments", icon: <Microscope size={18} /> },
  { to: "/telemetry", label: "Telemetry", icon: <Activity size={18} /> },
  { to: "/alerts", label: "Alerts", icon: <AlertTriangle size={18} /> },
  { to: "/equipment", label: "Equipment", icon: <Wrench size={18} /> },
  { to: "/events", label: "Scheduled Events", icon: <CalendarDays size={18} /> },
  { to: "/mission-assignments", label: "Mission Assignments", icon: <ClipboardList size={18} /> },
  { to: "/spacecraft-missions", label: "Spacecraft Missions", icon: <Sparkles size={18} /> },
  { to: "/experiment-executions", label: "Experiment Runs", icon: <FlaskConical size={18} /> },
  { to: "/module-integrations", label: "Module Integrations", icon: <Link2 size={18} /> },
  { to: "/profile", label: "My Profile", icon: <User size={18} /> },
];
